name = "myportfolio-api-proxy"
main = "cloudflare/src/index.js"
compatibility_date = "2026-09-13"

[[d1_databases]]
binding = "DB"
database_name = "myportfolio-db"
database_id = "382fd818-7124-474c-8170-22784eae3e83"
migrations_dir = "cloudflare/migrations"

[vars]
REPLY_FROM_EMAIL = "yangdarenaud893@gmail.com"
